apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: share
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: wordpress
  ports:
  - name: wordpress
    port: 5050
    protocol: TCP
    targetPort: 5050

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: docker_img_wordpress
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: wp-nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: wp-nginx-config
        configMap:
          name: wordpress-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wp-nginx.conf: |
    server {
      listen 5050;

      root /var/www/wordpress;
      index index.php;
    
      location / {
        try_files $uri $uri/ /index.php?$args;
      }

      location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
    }
